# config/settings.py 
 
TELEGRAM_API_KEY = "YOUR_TELEGRAM_API_KEY" 
SPORTSBOOK_API_KEY = "YOUR_SPORTSBOOK_API_KEY" 
TELEGRAM_GROUP_ID = "YOUR_TELEGRAM_GROUP_ID" 
SPORTSBOOK_URL = "https://sportsbook.example.com" 
